### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by theKashey** [sindresorhus/require-fool-webpack#1]
There is no `require` in real - webpack replaces it with it's own variant.
Shouldn't this work like?
```js
module.exports = typeof __webpack_require__ !== 'undefined' ? __webpack_require__ : require
```

**Comment by sindresorhus** [comment]
> There is no require in real

I'm not sure what you mean by "real"?

**Comment by theKashey** [comment]
I mean `require` exists only for nodejs application, and in case of webpack it might be not defined. Webpack injects __webpack_require__, and next replaces all the occurrences of require.

**Comment by sindresorhus** [comment]
Right, I guess I should document that. My use-case was for Node.js and Electron only.

**Comment by theKashey** [comment]
But you have created a library to fool webpack :D
```js
module.exports = eval('typeof __webpack_require__ !== 'undefined' ? __webpack_require__ : require');
```
then?

**Comment by sindresorhus** [comment]
Sure, wanna do a PR?

**Comment by theKashey** [comment]
Easy.
